### ISSUE TITLE
./mmh_darwin_amd64 install error

### ISSUE THREAD

**Issue by ghostsf** [mritd/mmh#12]
./mmh_darwin_amd64 install 
then .
get context failed

**Comment by mritd** [comment]
@ghostsf The new version of the configuration file structure has been changed, please execute `mv ~/.mmh ~/.mmh_bak` to back up the original configuration, then execute `mmh install` (mmh will automatically generate the example configuration)

**Comment by ghostsf** [comment]
> @ghostsf The new version of the configuration file structure has been changed, please execute `mv ~/.mmh ~/.mmh_bak` to back up the original configuration, then execute `mmh install` (mmh will automatically generate the example configuration)

ok,I got it,thanks!
