### ISSUE TITLE
安装go mod的依赖出现问题

### ISSUE THREAD

**Issue by cg831344** [mritd/mmh#14]
你好
通过 go mod download 发现版本无法找到呢
go: finding github.com/mritd/readline v0.0.0-20180425151209-ae245b60ddeb
go: github.com/mritd/readline@v0.0.0-20180425151209-ae245b60ddeb: unknown revision ae245b60ddeb
go: error loading module requirements

**Comment by mritd** [comment]
请暂时使用预编译版本，这个问题产生原因:

- 一开始由于终端提示库不支持中文，所以自己基于 readline 创建了 promptx 库
- 大约 1 年前开始向主流 prompt 库提交  PR 以支持中文(https://github.com/AlecAivazis/survey/pull/217)
- 在提交完完成后我已经开始着手替换相关终端提示库，并且删除了 promptx 和 readline
- 在删除了自己的 promptx 后，由于上游 survey 作者一直拖，最终导致合并失败(具体见 PR，开了 2 个左右)

最终造成了现在的  readline 丢失，再加上最近确实比较忙，暂时没去处理这个问题

**Comment by cg831344** [comment]
好的，谢谢
