### ISSUE TITLE
可以实现类似 ssh -D 的功能吗？

### ISSUE THREAD

**Issue by TimeBye** [mritd/mmh#15]
@mritd 你好，mmh 真的很好用，感谢进行分享。可以让 mmh 实现类似 ssh -D 的功能吗？有时候一些地址只能在内网中进行访问，如果 mmh 能打一个隧道就更爽了

**Comment by mritd** [comment]
我有时间尝试实现一下

**Comment by mritd** [comment]
@TimeBye v1.4.0 已经发布，请测试一下 tunnel 能力是否满足需求

**Comment by TimeBye** [comment]
@mritd 刚刚尝试了一下    tunnel功能很好用    谢谢大神
