### ISSUE TITLE
服务器增删命令

### ISSUE THREAD

**Issue by Jisxu** [mritd/mmh#18]
为什么在1.4版本中去掉了mmh server add/remove命令

**Comment by mritd** [comment]
> 为什么在1.4版本中去掉了mmh server add/remove命令

😅 感觉用的不多，还没有直接编辑 yaml 方便，而且还涉及到配置文件排序啥的，当时感觉实用价值有点小

**Comment by Jisxu** [comment]
希望加回来，我使用add命令挺多，一般是加完server然后进配置文件微调

**Comment by mritd** [comment]
> 希望加回来，我使用add命令挺多，一般是加完server然后进配置文件微调

好的，我下个版本添加回来 😂

**Comment by mritd** [comment]
@Jisxu 1.4.2 pre release
