### ISSUE TITLE
可以自定义配置文件目录吗？

### ISSUE THREAD

**Issue by qinkangdeid** [mritd/mmh#19]
习惯性吧工作的文件方一个文件夹 例如 work   不知可以否🙏

**Comment by mritd** [comment]
直能说部份支持，我目前的方案是:

- 将主要配置文件放置在 iCloud/MEGA 等加密同步的网盘中
- 在 `~/.mmh/main.yaml` 中指定 context 相应文件位置

**Comment by qinkangdeid** [comment]
好的 明白了
