### ISSUE TITLE
max_proxy 影响 tun 模式下 TCP 隧道

### ISSUE THREAD

**Issue by mritd** [mritd/mmh#20]
在 issue #15 commit 0ae677483a08b39931e0291f6a23d4807d774e3f 中增加了跳板模式的 tcp tunnel 能力；由此产生了对于 "无限跳板" 安全边界判断的一个 bug:

默认情况下最大跳板机数量(max_proxy)为 5，为了防止用户写错配置文件从而导致循环链接的情况；此种限止在 tcp tunnel 模式下不适用，因为**max_proxy  存储在同一个实例中，多个 tcp 链接打开会不断增加此数值直到触发警界值**；目前解决方案:

1、增加一个标志位，在 tcp tunnel 模式下忽略安全警界值(max_proxy)，不过有安全风险
2、将 max_proxy 关联当前 goroutine id，不过对 tcp 链接性能有影响

**Comment by mritd** [comment]
@TimeBye 你感觉哪种解决方案跟好点？

**Comment by TimeBye** [comment]
现在才看到这个issues，实在不好意思。我这边使用 `mmh` 基本上都是直连到机器的，所以没有测试到有跳板机的情况。个人觉得还是方案2要好一点，即使性能差点我觉得应该还是感觉不出来吧 😂，方案一的话就怕误配置无限循环下去，当局者迷嘛。

**Comment by mritd** [comment]
我尝试实现一下，目前是 在 tcp tun 模式下禁用了 max_proxy 检测

**Comment by mritd** [comment]
@TimeBye v1.5.2 版本通过重构递归调用，将 max_proxy 计数调整到单个 goroutine 内实现了多 tcp 链接下的安全边界检测(对性能基本无影响，没有去尝试获取 goroutine id)；同时大幅度优化了 tun 模式下单个链接打开速度。

**Comment by TimeBye** [comment]
大神真给力，马上升级体验😋

**Comment by TimeBye** [comment]
@mritd 新版本中取消了 `main.yaml` 的相关配置吗？文档这里是否需要删除相关信息呢？

https://github.com/mritd/mmh#mainyaml

**Comment by mritd** [comment]
@TimeBye 正在编写文档，目前感觉文档描述有点烂 哈哈

**Comment by TimeBye** [comment]
@mritd 大神，少了 `main.yaml` 配置现在对 `context` 怎么进行排序呢？默认用的文件名感觉不是太友好，还有以前把跳板机写在 `basic` 里面就可以了，现在是需要每个 `context` 都写一个了哇？

**Comment by mritd** [comment]
@TimeBye 我正在编写文档，你可以先访问 http://mmh.mritd.me 预览，里面详细描述了一些配置的设计思路，不过我还在编写中，可能随时有变更。
