### ISSUE TITLE
堡垒机登陆

### ISSUE THREAD

**Issue by currycan** [mritd/mmh#32]
您好！
首先必须先吹捧一下，工具真的好用，比配置ssh config方便多了。
最近在使用过程中发现，登陆堡垒机貌似不能用，具体如下：
1、配置堡垒机的登陆账户密码等
2、登陆，由于需要双向认证，输入接收到的短信验证码后才能继续
3、登陆报错：
😱 ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain

**Comment by mritd** [comment]
能否使用 `ssh -vvv user@address` 尝试连接一下堡垒机然后提供一下连接日志(**注意相关隐私打码**)

**Comment by mritd** [comment]
根本原因应该是目前 ssh 的 auth method 不支持，以下是 ssh 的一些 auth method:

- Password authentication: Client will ask you to enter a password, will encrypt it and use it to authenticate itself to a server.
- Public key authentication: Each client uses a key pair to authenticate itself to a server. Server should find the key in the list of allowed keys.
- Host based authentication: This method is similar to public key authentication, but client should not only use correct key, but also must connect from correct host.
- Keyboard authentication: Server will use client to present zero or more prompts to client PC operator and request answers from operator.
- Challenge Response Authentication: Used to configure keyboard authentication. You should use specific backend send the challenges and check the responses.
- GSSAPI Authentication: GSSAPI is a IETF standard for strong encrypted authentication. OpenSSH uses GSSAPI and kerberos 5 code to authenticate clients.

由于 mmh 需要自动化，所以目前仅支持了 password 和 public key 这两种认证方式；一般跳板机会采用键盘挑战等认证方式，尤其在短信验证上是很难做自动化的；如果可以的化你发我一下日志，我看一下有没有办法把这些特殊的 method 抽出来让用户自己处理

**Comment by currycan** [comment]
信息如下：
![ssh-info](https://tva1.sinaimg.cn/large/007S8ZIlgy1gfdu5dslunj30u03jpu12.jpg)

**Comment by mritd** [comment]
从日志上显示是服务端发送了 KeyboardInteractive(键盘交互挑战)，这个在理论上 mmh 可以实现这种挑战，甚至将此类挑战单独抽到外部来让用户通过自定义脚本通过这个挑战；**但是最大的问题在于一旦通过此挑战，堡垒机发送了一个选择列表来让用户选择，这个过程已经不再属于 ssh 认证部分，所以 ssh 无法再进行干预(数据流将直接转发到 raw 终端，mmh 无法修改)**；所以目前根据我的猜测是即使 mmh 完成键盘挑战，也无法进行继续穿透，这个结果我在 jumpserver 上测试过。

**Comment by mritd** [comment]
其实我个人挺反感这种堡垒机设计，本质上来讲有些东西脱离了 ssh，导致我们没办法通过一些标准的方式去处理它；如果自己用的话倒是有一些办法:

- mmh 接收并完成键盘挑战
- mmh 针对 ssh stdin/out 对接到 raw 终端
- mmh sleep 指定时间等待 server 端推送服务器列表
- mmh 通过预定格式将文本强制 print 到 stdin 促使 server 端跳转

这种操作问题也很明显:

- mmh 必须精确得知键盘挑战通过后服务端需要输入的服务器格式(显然不同跳板机都不同)
- mmh 在等待服务端推送服务器列表这段时间无法精确确定(sleep)

**Comment by currycan** [comment]
的确！这种模式就是脱离了ssh原有模式，但是从安全的角度考虑也有现实意义。
可能纯命令式的ssh工具很难解决这个问题，配合GUI的界面上兴许可以，个人着实对这块也没太多研究，只能说是喜欢一款工具，就希望其近乎完美，能满足各种场景！

**Comment by mritd** [comment]
我有时间尝试一下看看是否可以开放给用户做自定义 hook

**Comment by jumping** [comment]
这个是明御的堡垒机，开启短信授权了，就无法登陆了。

**Comment by mritd** [comment]
我准备后面试试能不能做个 hook，ssh 登录完成以后把  stdin/out 拿出来提供给用户，然后用户可以用一些自定义脚本处理它；最近有点忙还没去实现，还不知道是否可行。

**Comment by mritd** [comment]
@jumping @currycan 在新版本已经准备好了两个 hook 点:

针对键盘挑战(KeyboardInteractive) 提供 `server.keyboard_auth_cmd` 配置，该配置指定一个命令(可能是一个小脚本或者其他的可执行命令)用来完成挑战，在进行挑战时 ssh server 发送的键盘交互请求将会以  json 的形式对接到指定命令的 stdin，用户可以读取并处理后通过 stdout 按行返回结果，然后 mmh 响应给 ssh server，常见的比如 OTP 认证都可以通过此种方式实现自动化。

针对登录成功后的选择界面提供 `server.hook_cmd` 配置，该配置同样指定一个命令用来接收 server 的输出并并通过 stdout 返回响应；命令的 stdout 将会作为 stdin 发往  ssh server，从而实现一些登录后 hook；这个 hook 点可以实现自动选择菜单、自动 sudo 等。

**Comment by mritd** [comment]
v1.5.4 release
