### ISSUE TITLE
这个可以在jumpserver上跳转吗

### ISSUE THREAD

**Issue by wilsonjwz** [mritd/mmh#34]

**Comment by mritd** [comment]
要看你得 jumbserver 怎么设置的，工具提供了 两个 hook 用来自动选择 stdout 给出的列表；hook 脚本需要你自己写，具体你可以查看 https://mmh.mritd.me/05-advanced

**Comment by wilsonjwz** [comment]
还有一个小问题 
![image](https://user-images.githubusercontent.com/30870262/93319603-a5b73a00-f842-11ea-9913-fef22383d9c1.png)

**Comment by wilsonjwz** [comment]
按照你的来 发现解析失败了

**Comment by mritd** [comment]
脚本 你要自己编写的，因为每个人的情况不同，而且脚本要自己增加可执行权限。

**Comment by wilsonjwz** [comment]
我需要先测试 脚本的可行性

# 发送切换命令
echo "sudo su - root && exit"
# 延迟 0.5s 发送密码
sleep 0.5
echo "password"

但用这个的时候也不行

**Comment by mritd** [comment]
报错日志有么？

**Comment by wilsonjwz** [comment]
就是截图那个

**Comment by wilsonjwz** [comment]
![image](https://user-images.githubusercontent.com/30870262/93325989-bff51600-f84a-11ea-885d-78c2db9be01f.png)

**Comment by mritd** [comment]
给脚本加可执行权限

**Comment by wilsonjwz** [comment]
有加过 777 跟 600了

**Comment by wilsonjwz** [comment]
![image](https://user-images.githubusercontent.com/30870262/93410425-8e705f00-f8cb-11ea-8674-3c7f031435eb.png)
`chmod +x hook_sudo_su_root.sh`
加了这个 一样不行

**Comment by mritd** [comment]
Shebang 头加了么？

**Comment by wilsonjwz** [comment]
Shebang 头是什么 估计没有

**Comment by wilsonjwz** [comment]
![image](https://user-images.githubusercontent.com/30870262/93413375-bc58a200-f8d1-11ea-916c-292cb160533b.png)
只有你在文档上的那些

**Comment by mritd** [comment]
第一行加上 #!/use/bin/env bash

**Comment by wilsonjwz** [comment]
嗯嗯嗯 可以了 
就是感觉跟别的有点延迟 是正常的吗

**Comment by mritd** [comment]
连接延迟 跟 你使用 ssh 基本是一致的，至于后续的脚本延迟 那就看你怎么写了，毕竟是 hook 不是正经 api

**Comment by wilsonjwz** [comment]
明白 可能是服务器上网络的问题
