### ISSUE TITLE
发现 使用mec的时候 没有调用hook交互 可以先调用hook交互 再执行exec相关命令

### ISSUE THREAD

**Issue by wilsonjwz** [mritd/mmh#35]
因为 我需要进入到跳板机之后 再去进入对应的服务器上执行 exec的相关操作

**Comment by wilsonjwz** [comment]
可以 期待 这样的话 可以极大加快效率了

**Comment by mritd** [comment]
很抱歉，最近测试了一下这是不可行的，原因如下:

[RFC 4254 的 #section-6.5](https://tools.ietf.org/html/rfc4254#section-6.5) 的规范是每一个 channel 只能有一个 req 能执行成功，而标准的 ssh 远端执行命令 调用的是 exec 这个 req，在 exec 这个 req 下没有办法确定时机来 hook stdin，或者说 exec 直接把要执行的命令发到了 server 端，没有机会做 hook。
