### ISSUE TITLE
配置 hook_cmd 出现  permission denied

### ISSUE THREAD

**Issue by AboutCXJ** [mritd/mmh#40]
System:MacOS11.1
mmh:1.5.4
<img width="570" alt="截屏2021-01-30 01 26 46" src="https://user-images.githubusercontent.com/19811825/106307420-4fe7a980-629a-11eb-9ea1-c5230e316fd3.png">
<img width="1032" alt="截屏2021-01-30 01 27 02" src="https://user-images.githubusercontent.com/19811825/106307433-54ac5d80-629a-11eb-88a9-74008900807f.png">

**Comment by mritd** [comment]
尝试一下给 shell 脚本加可执行权限: `chmod +x test.sh`

**Comment by AboutCXJ** [comment]
> 尝试一下给 shell 脚本加可执行权限: `chmod +x test.sh`

解决了，感谢大佬，项目很棒！
