### ISSUE TITLE
不能账户+密码登陆，显示ssh的key问题

### ISSUE THREAD

**Issue by chuntaojun** [mritd/mmh#6]
无法使用username+password的方式登陆，说
`open /Users/liaochuntao/.ssh/id_rsa: no such file or directory`

**Comment by mritd** [comment]
请提供一下配置

**Comment by mritd** [comment]
@chuntaojun 已经修复了，不给过这个新版本需要大于明天才能发布；新版本增加了多配置文件(conetx) 支持，以及 context 自动降级

**Comment by chuntaojun** [comment]
@mritd 好的，谢谢
