### ISSUE TITLE
请教，具体怎么安装的？mac

### ISSUE THREAD

**Issue by of0** [mritd/mmh#9]

**Comment by of0** [comment]
用的oh my zsh 输入mmh --help后提示zsh: command not found: mmh

**Comment by of0** [comment]
默认安装的时候提示没有权限，我使用--dir安装到了其他目录，会不会是这个原因导致直接在命令行输入mmh没有反应的？

**Comment by of0** [comment]
添加了环境变量就好了，原来是如果在usr/bin下就没关系，如果没权限安装到usr/bin下添加一下环境变量就ok了。
麻烦了～

**Comment by mritd** [comment]
对的 ，`--dir` 就是为了保证 `/usr/bin` 没权限时使用的
